name: Build Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_check:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Run Production Build
        run: pnpm build
